experiment_configs = {
    "1": {
        "description": "Replacing the apex predator with super predator",
        "data_path": "output/experiments/results/Experiment-1_results.csv",
        "status": "skip",
        "n_models": 2,
        "populations": ["Prey", "Predator", "Apex"],
        "variables": ["s_breed", "f_breed"],
        "models": ["Apex", "Super"],
    },
    "2": {
        "description": "Varying the target and lethality of superpredators",
        "data_path": "output/experiments/results/Experiment-2_results.csv",
        "status": "pending",
        "n_models": 6,
        "populations": ["Prey", "Predator"],
        "variables": ["s_breed", "f_breed"],
        "models": [
            f"{leth} -> {t}"
            for leth in ["Non-lethal", "Lethal"]
            for t in ["Prey", "Predator", "Both"]
        ],
    },
    "3": {
        "description": "Determining the effects of predator and prey information",
        "data_path": "output/experiments/results/Experiment-3_results.csv",
        "status": "pending",
        "n_models": 4,
        "populations": ["Prey", "Predator"],
        "variables": ["s_breed", "f_breed"],
        "models": [
            "Both Informed",
            "Prey Informed",
            "Predator Informed",
            "Both Naive",
        ],
    },
    "4a": {
        "description": "Effect of handling limit on mesopredator",
        "data_path": "output/experiments/results/Experiment-4_lv_results.csv",
        "status": "skip",
        "n_models": 1,
        "populations": ["Prey", "Predator"],
        "variables": ["s_max"],
        "n_params": 50,
        "models": ["LV"],
    },
    "4b": {
        "description": "Effect of handling limit on apex predator",
        "data_path": "output/experiments/results/Experiment-4_apex_results.csv",
        "status": "skip",
        "n_models": 1,
        "populations": ["Prey", "Predator", "Apex"],
        "variables": ["a_max"],
        "n_params": 50,
        "models": ["Apex"],
    },
    "5": {
        "description": "Varying birth rates of apex predator",
        "data_path": "output/experiments/results/Experiment-5_results.csv",
        "status": "skip",
        "n_models": 1,
        "n_params": 50,
        "populations": ["Prey", "Predator", "Apex"],
        "variables": ["a_breed"],
        "models": ["Apex"],
    },
    "6": {
        "description": "Varying lattice size and local saturation of prey for LV model",
        "data_path": "output/experiments/results/Experiment-6_results.csv",
        "status": "pending",
        "n_models": 4,
        "n_params": 8,
        "populations": ["Prey"],
        "variables": ["f_max"],
        "models": [r"L^{2} = 10", r"L^{2} = 20", r"L^{2} = 50", r"L^{2} = 100"],
        "reps": 10,
        "steps": 2000,
    },
    "7": {
        "description": "Varying lethality of mesopredator",
        "data_path": "output/experiments/results/Experiment-7_results.csv",
        "status": "skip",
        "n_models": 1,
        "n_params": 50,
        "populations": ["Prey", "Predator"],
        "variables": ["s_lethality"],
        "models": ["LV"],
    },
    "8": {
        "description": "Varying lethality of apex predator",
        "data_path": "output/experiments/results/Experiment-8_results.csv",
        "status": "skip",
        "n_models": 1,
        "n_params": 20,
        "populations": ["Prey", "Predator", "Apex"],
        "variables": ["a_lethality"],
        "models": ["Apex"],
    },
}
